new_columns = {'Form Name': 'formName_{suffix}',
               'Hospital': 'hospital',
               'User Name': 'userName',
               'אבחנה-Age': 'age',
               'אבחנה-Basic stage': 'basicStage',
               'אבחנה-Diagnosis date': 'diagnosisDate',
               'אבחנה-Her2': 'her2',
               'אבחנה-Histological diagnosis': 'histologicalDiagnosis',
               'אבחנה-Histopatological degree': 'histopatologicalDegree',
               'אבחנה-Ivi -Lymphovascular invasion': 'lymphovascularInvasion',
               'אבחנה-KI67 protein': 'KI67_protein',
               'אבחנה-Lymphatic penetration': 'lymphaticPenetration',
               'אבחנה-M -metastases mark (TNM)': 'mMetastasesMarkTNM',
               'אבחנה-Margin Type': 'marginType',
               'אבחנה-N -lymph nodes mark (TNM)': 'lymphNodesMarkTNM',
               'אבחנה-Nodes exam': 'nodesExam',
               'אבחנה-Positive nodes': 'positiveLymph',
               'אבחנה-Side': 'side',
               'אבחנה-Stage': 'stage',
               'אבחנה-Surgery date1': 'surgeryDate1',
               'אבחנה-Surgery date2': 'surgeryDate2',
               'אבחנה-Surgery date3': 'surgeryDate3',
               'אבחנה-Surgery name1': 'surgeryName1',
               'אבחנה-Surgery name2': 'surgeryName2',
               'אבחנה-Surgery name3': 'surgeryName3',
               'אבחנה-Surgery sum': 'surgerySum',
               'אבחנה-T -Tumor mark (TNM)': 'tumorMarkTNM',
               'אבחנה-Tumor depth': 'tumorDepth',
               'אבחנה-Tumor width': 'tumorWidth',
               'אבחנה-er': 'er',
               'אבחנה-pr': 'pr',
               'surgery before or after-Activity date': 'activityDate',
               'surgery before or after-Actual activity': 'actualActivity',
               'id-hushed_internalpatientid': 'id'}
